# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black == 22.1.0]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ['--ignore=E712,E24,W504,W503,E203,E501']
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-lll, --recursive, .]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
        - id: isort
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        exclude: ^(tests|server/api/|server/models/|manage.py|server/__init__.py)
        args: [-vv, -i, --fail-under=60]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        exclude: (tests/|server/models/|manage.py)
        args: [--strict, --ignore-missing-imports, --no-warn-return-any, --allow-subclassing-any, --allow-untyped-decorators]
