version: "3"
services:
  monopoly:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: monopoly-challenge
    volumes:
      - .:/monopoly
    restart: on-failure
    stdin_open: true
    tty: true
